---
- hosts: imageservers
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - git:
        repo=https://github.com/at-grandpa/isucon5-qualify.git
        dest=/tmp/isucon5-qualify
    - shell: |
        mysqladmin -uroot -proot -hisucon5q-crystal-mysql create isucon5q
        cat /tmp/isucon5-qualify/webapp/sql/schema.sql | mysql -uroot -proot -hisucon5q-crystal-mysql isucon5q
        for table in users salts relations profiles entries comments footprints ; do echo "ALTER TABLE ${table} ROW_FORMAT=compressed;" ; done | mysql -uroot -proot -hisucon5q-crystal-mysql isucon5q
        export PATH=/home/isucon/.local/ruby/bin:$PATH
        cd /tmp/isucon5-qualify/webapp/script && bundle install
        cd /tmp/isucon5-qualify/webapp/script && ./gen.rb gen_users
        cd /tmp/isucon5-qualify/webapp/script && ./gen.rb gen_relations
        cd /tmp/isucon5-qualify/webapp/script && ./gen.rb gen_entries
        cd /tmp/isucon5-qualify/webapp/script && ./gen.rb gen_comments
        cd /tmp/isucon5-qualify/webapp/script && ./gen.rb gen_footprints
        cd /tmp/isucon5-qualify/webapp/script && ./check_testsets.rb
        touch /tmp/done_mysql
      args:
        chdir: /tmp/isucon5-qualify/webapp/script
        creates: /tmp/done_mysql
    - command: rm -rf /tmp/isucon5-qualify
      args:
        removes: /tmp/isucon5-qualify

- hosts: imageservers
  gather_facts: no
  sudo: yes
  tasks:
    - name: copy my.cnf
      copy: src=../files/my.cnf dest=/etc/my.cnf owner=root mode=644
