---
- hosts: imageservers
  sudo: yes
  gather_facts: no
  tasks:
    - apt: name=nginx state=present
    - copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=644
    - copy: src=../files/nginx.php.conf dest=/etc/nginx/nginx.php.conf owner=root mode=644
    - name: copy root ~/.my.cnf
      copy: src=../files/my.cnf.root dest=/root/.my.cnf owner=root mode=644
    - name: copy my.cnf
      copy: src=../files/my.cnf.restore dest=/etc/my.cnf owner=root mode=644
    - apt: name=python-mysqldb state=present
    - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
